# asset pack configurations
[asset_pack]
    # asset pack name
    name =              "vzombies-assets"
    # contributors
    author =            "Voltaism"
    # version
    version =           "0.1.3"
    # image URL
    image =             "https://i.imgur.com/kjnOj4u.png"
    # unreal engine folder - the name of the root folder (the one inside UnrealProject/Content/) which the assets will have references to each other
    unreal_folder =     "vzombiesAssets"

# assets files
[assets]
    # maps
    [assets.maps]
        # MyMap = "MyFolder/MyAwesomeMap"
        # ...

    # static meshes
    [assets.static_meshes]
        carpenter = "Powerups/carpenter/carpenter"
        doubletap = "Perks/doubletap/doubletap"
        doubletap_bottle = "Perks/doubletap/bottle/doubletap_bottle"
        instakill = "Powerups/instakill/instakill"
        jugg_bottle = "Perks/juggernog/bottle/jugg_bottle"
        juggernog = "Perks/juggernog/juggernog"
        max_ammo = "Powerups/max_ammo/max_ammo"
        mystery_box = "MysteryBox/mystery_box"
        mystery_box_fake_bear = "MysteryBox/mystery_box_fake_bear"
        nuke = "Powerups/nuke/nuke"
        pack_a_punch = "Pack_a_punch/pack_a_punch"
        power_base = "Power/base/power_base"
        power_handle = "Power/handle/power_handle"
        revive = "Perks/quick_revive/revive"
        revive_bottle = "Perks/quick_revive/bottle/revive_bottle"
        three_gun = "Perks/three_gun/three_gun"
        three_gun_bottle = "Perks/three_gun/bottle/three_gun_bottle"
        x2 = "Powerups/x2/x2"

    # skeletal meshes
    [assets.skeletal_meshes]
        SK_TSZombie = "Zombies/TShirtZombie/Mesh/SK_TSZombie"
        SK_TSZombie2 = "Zombies/TShirtZombie/Mesh/SK_TSZombie2"
        SK_TSZombie3 = "Zombies/TShirtZombie/Mesh/SK_TSZombie3"
        SK_TSZombie4 = "Zombies/TShirtZombie/Mesh/SK_TSZombie4"
        SK_TSZombie_ArmL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_ArmL"
        SK_TSZombie_ArmR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_ArmR"
        SK_TSZombie_FootL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_FootL"
        SK_TSZombie_FootR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_FootR"
        SK_TSZombie_ForeArmL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_ForeArmL"
        SK_TSZombie_ForeArmR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_ForeArmR"
        SK_TSZombie_HandL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_HandL"
        SK_TSZombie_HandR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_HandR"
        SK_TSZombie_Head = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_Head"
        SK_TSZombie_KneeL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_KneeL"
        SK_TSZombie_KneeR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_KneeR"
        SK_TSZombie_LegL = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_LegL"
        SK_TSZombie_LegR = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_LegR"
        SK_TSZombie_Torso = "Zombies/TShirtZombie/Mesh/Parts/SK_TSZombie_Torso"

    # sounds
    [assets.sounds]
        attack_00 = "Sounds/Zombies/attack/attack_00"
        attack_01 = "Sounds/Zombies/attack/attack_01"
        attack_02 = "Sounds/Zombies/attack/attack_02"
        attack_03 = "Sounds/Zombies/attack/attack_03"
        attack_04 = "Sounds/Zombies/attack/attack_04"
        attack_05 = "Sounds/Zombies/attack/attack_05"
        attack_06 = "Sounds/Zombies/attack/attack_06"
        attack_07 = "Sounds/Zombies/attack/attack_07"
        attack_08 = "Sounds/Zombies/attack/attack_08"
        attack_09 = "Sounds/Zombies/attack/attack_09"
        attack_10 = "Sounds/Zombies/attack/attack_10"
        attack_11 = "Sounds/Zombies/attack/attack_11"
        attack_12 = "Sounds/Zombies/attack/attack_12"
        attack_13 = "Sounds/Zombies/attack/attack_13"
        attack_14 = "Sounds/Zombies/attack/attack_14"
        attack_15 = "Sounds/Zombies/attack/attack_15"
        barricade_repair = "Sounds/Barricades/barricade_repair"
        behind_00 = "Sounds/Zombies/behind/behind_00"
        behind_01 = "Sounds/Zombies/behind/behind_01"
        behind_02 = "Sounds/Zombies/behind/behind_02"
        behind_03 = "Sounds/Zombies/behind/behind_03"
        behind_04 = "Sounds/Zombies/behind/behind_04"
        buy_accept = "Sounds/buy_accept"
        carpiter = "Sounds/Powerups/carpiter"
        crawl_00 = "Sounds/Zombies/crawl/crawl_00"
        crawl_01 = "Sounds/Zombies/crawl/crawl_01"
        crawl_02 = "Sounds/Zombies/crawl/crawl_02"
        crawl_03 = "Sounds/Zombies/crawl/crawl_03"
        crawl_04 = "Sounds/Zombies/crawl/crawl_04"
        crawl_05 = "Sounds/Zombies/crawl/crawl_05"
        death_00 = "Sounds/Zombies/die/death_00"
        death_01 = "Sounds/Zombies/die/death_01"
        death_02 = "Sounds/Zombies/die/death_02"
        death_03 = "Sounds/Zombies/die/death_03"
        death_04 = "Sounds/Zombies/die/death_04"
        death_05 = "Sounds/Zombies/die/death_05"
        death_06 = "Sounds/Zombies/die/death_06"
        death_07 = "Sounds/Zombies/die/death_07"
        death_08 = "Sounds/Zombies/die/death_08"
        death_09 = "Sounds/Zombies/die/death_09"
        death_10 = "Sounds/Zombies/die/death_10"
        drink_perk_rrr = "Sounds/Perks/drink_perk_rrr"
        grab = "Sounds/Powerups/grab"
        instakill = "Sounds/Powerups/instakill"
        laststand_enter = "Sounds/Player/laststand/laststand_enter"
        laststand_exit = "Sounds/Player/laststand/laststand_exit"
        laststand_loop = "Sounds/Player/laststand/laststand_loop"
        lowhealth_enter = "Sounds/Player/low_health/lowhealth_enter"
        lowhealth_exit = "Sounds/Player/low_health/lowhealth_exit"
        lowhealth_lp = "Sounds/Player/low_health/lowhealth_lp"
        maxammo = "Sounds/Powerups/maxammo"
        mbox_child = "Sounds/mbox/mbox_child"
        mbox_music_box = "Sounds/mbox/mbox_music_box"
        mbox_open = "Sounds/mbox/mbox_open"
        mus_zombie_round_over = "Sounds/Rounds/mus_zombie_round_over"
        mus_zombie_round_start = "Sounds/Rounds/mus_zombie_round_start"
        mx_game_over = "Sounds/Rounds/mx_game_over"
        nuke = "Sounds/Powerups/nuke"
        p_loop = "Sounds/Powerups/p_loop"
        p_spawn = "Sounds/Powerups/p_spawn"
        pap_ready = "Sounds/pap/pap_ready"
        pap_upgrade = "Sounds/pap/pap_upgrade"
        power_on = "Sounds/power_on"
        power_on_3D = "Sounds/power_on_3D"
        slam_00 = "Sounds/Barricades/slam/slam_00"
        slam_01 = "Sounds/Barricades/slam/slam_01"
        slam_02 = "Sounds/Barricades/slam/slam_02"
        slam_03 = "Sounds/Barricades/slam/slam_03"
        slam_04 = "Sounds/Barricades/slam/slam_04"
        slam_05 = "Sounds/Barricades/slam/slam_05"
        snap_00 = "Sounds/Barricades/snap/snap_00"
        snap_01 = "Sounds/Barricades/snap/snap_01"
        snap_02 = "Sounds/Barricades/snap/snap_02"
        snap_03 = "Sounds/Barricades/snap/snap_03"
        snap_04 = "Sounds/Barricades/snap/snap_04"
        snap_05 = "Sounds/Barricades/snap/snap_05"
        soft_00 = "Sounds/Zombies/soft/soft_00"
        soft_01 = "Sounds/Zombies/soft/soft_01"
        soft_02 = "Sounds/Zombies/soft/soft_02"
        soft_03 = "Sounds/Zombies/soft/soft_03"
        soft_04 = "Sounds/Zombies/soft/soft_04"
        soft_05 = "Sounds/Zombies/soft/soft_05"
        sprint_00 = "Sounds/Zombies/sprint/sprint_00"
        sprint_01 = "Sounds/Zombies/sprint/sprint_01"
        sprint_02 = "Sounds/Zombies/sprint/sprint_02"
        sprint_03 = "Sounds/Zombies/sprint/sprint_03"
        sprint_04 = "Sounds/Zombies/sprint/sprint_04"
        sprint_05 = "Sounds/Zombies/sprint/sprint_05"
        sprint_06 = "Sounds/Zombies/sprint/sprint_06"
        sprint_07 = "Sounds/Zombies/sprint/sprint_07"
        sprint_08 = "Sounds/Zombies/sprint/sprint_08"
        x2 = "Sounds/Powerups/x2"
        zombie_hit_player_00 = "Sounds/Player/hit_player/zombie_hit_player_00"
        zombie_hit_player_01 = "Sounds/Player/hit_player/zombie_hit_player_01"
        zombie_hit_player_02 = "Sounds/Player/hit_player/zombie_hit_player_02"
        zombie_hit_player_03 = "Sounds/Player/hit_player/zombie_hit_player_03"
        zombie_hit_player_04 = "Sounds/Player/hit_player/zombie_hit_player_04"
        zombie_hit_player_05 = "Sounds/Player/hit_player/zombie_hit_player_05"

    # animations
    [assets.animations]
        MOB_Stand_to_Zombie_Idle_1_v2_IPC = "Zombies/Animation/In_Place_Retarget/MOB_Stand_to_Zombie_Idle_1_v2_IPC"
        Zombie_Atk_Arms_3_SHORT_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Atk_Arms_3_SHORT_Loop_IPC"
        Zombie_Atk_Loop_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Atk_Loop_1_IPC"
        Zombie_Chase_1_KnockBack_Chase_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Chase_1_KnockBack_Chase_IPC"
        Zombie_Chase_1_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Chase_1_Loop_IPC"
        Zombie_Crawl_1_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Crawl_1_Loop_IPC"
        Zombie_Death_Back_Mid_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Death_Back_Mid_1_IPC"
        Zombie_Death_Hit_Back_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Death_Hit_Back_1_IPC"
        Zombie_HyperAttack_1_SHORT_Idle_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_HyperAttack_1_SHORT_Idle_Loop_IPC"
        Zombie_HyperAttack_1_SHORT_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_HyperAttack_1_SHORT_Loop_IPC"
        Zombie_HyperChase_1_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_HyperChase_1_Loop_IPC"
        Zombie_Idle_1_v2_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Idle_1_v2_IPC"
        Zombie_Idle_1_v2_to_MOB_Stand_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Idle_1_v2_to_MOB_Stand_IPC"
        Zombie_Idle_2_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Idle_2_IPC"
        Zombie_OnFire_2A_SHORT_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_OnFire_2A_SHORT_IPC"
        Zombie_Reach_1_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Reach_1_Loop_IPC"
        Zombie_Stand_To_Atk_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Stand_To_Atk_1_IPC"
        Zombie_Stand_To_Chase_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Stand_To_Chase_1_IPC"
        Zombie_Stand_Walk_F_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Stand_Walk_F_1_IPC"
        Zombie_Stand_to_Crawl_1_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Stand_to_Crawl_1_IPC"
        Zombie_Walk_F_1_KnockBack_Walk_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Walk_F_1_KnockBack_Walk_IPC"
        Zombie_Walk_F_1_Loop_IPC = "Zombies/Animation/In_Place_Retarget/Zombie_Walk_F_1_Loop_IPC"

    # particles
    [assets.particles]
        PS_Powerup = "Powerups/PS_Powerup"

    # materials
    [assets.materials]
        M_Pack_a_punch = "Pack_a_punch/weapon/M_Pack_a_punch"
        M_Plank = "Z_barricade/Mats/M_Plank"

    # other assets (for not yet categorized ones)
    [assets.others]
        # A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
        # ...
